### ISSUE TITLE
Something wrong about the datasets ShapeNet-ViPC

### ISSUE THREAD

**Issue by chenlongwhu** [diegovalsesia/XMFnet#1]
When I run the command ```cat ShapeNetViPC-Dataset.tar.gz* | tar zx``` , I only get the corresponding images (ShapeNetViPC-View). So, what can I do to get the corresponding partial and complete point clouds?

**Comment by Emanuele97x** [comment]
Hi Chen Long Whu, 

Currently the dataset is provided by the authors of "View-guided Point Cloud Completion".  When I downloaded it following their instructions everything was fine, are you sure to have completely downloaded all the dataset (143GB)?

**Comment by chenlongwhu** [comment]
Thank you! I think I have found the problem.
