### ISSUE TITLE
Could you offer the camera_calibration.txt file?

### ISSUE THREAD

**Issue by zhanghm1995** [diegovalsesia/XMFnet#10]
@Emanuele97x Hi, I found that you load the `camera_calibration.txt` in `ViPCDataLoader_ft` class when training the model in weakly supervised manner. However, I don't have this file at all.

Could you offer this file? Thanks in advance.

**Comment by Emanuele97x** [comment]
Hi! @zhanghm1995 
These files are present in the view folder in the dataset, just for the objects we use for the weakly supervised training (you can find them in `train_list_clean_.....txt` files). Hope you find it!

Best,

Emanuele

**Comment by zhanghm1995** [comment]
Hi, I'm not sure whether I missed something. I cannot find this file after extracting the dataset as below.
![image](https://user-images.githubusercontent.com/24753281/221812118-be1e7a6d-19c8-4146-972e-94e0264ee7d9.png)

And from your descriptions, I wonder are the camera parameters same for all objects or different for each object?

**Comment by Emanuele97x** [comment]
They are inside the folder of each specific object, indeed if you look at the dataloader for each object we extract `camera_calibration.txt `and `rendering_metadata.txt`.

**Comment by zhanghm1995** [comment]
@Emanuele97x , sorry to ask you again. I don't know why I cannot find the `camera_calibration.txt` in my original extracted dataset, 

![image](https://user-images.githubusercontent.com/24753281/221841380-b9ed5fde-3c90-44d0-aa3b-17bb0b242617.png),

I guess these files maybe exist in your `ShapeNetViPC-PartPart.tar.gz` file, and I'm downloading it at the same time to see what's wrong. In this case, I wonder to know how to generate the `camera_calibration.txt` file for the whole ShapeNet-ViPC dataset.

**Comment by Emanuele97x** [comment]
The file is present only for the selected obects, please check `train_list_clean_plane.txt` for an example.

**Comment by zhanghm1995** [comment]
@Emanuele97x , so it means we can only obtain the `camera_calibration.txt` in those selected objects? Is there any way to get the camera parameters for all objects?
