### ISSUE TITLE
Some questions about replicating the results.

### ISSUE THREAD

**Issue by engqing** [diegovalsesia/XMFnet#12]
![image](https://user-images.githubusercontent.com/115127943/226095840-5e0921d9-2982-4293-9465-603e383224ee.png)
I downloaded your pretrained models, but the results seem to vary widely when testing the category of airplane

**Comment by Emanuele97x** [comment]
Hi @engqing, I just checked and I am able to replicate our results! Does this issue appears only in plane category or also for other categories? Thanks!

**Comment by engqing** [comment]
![image](https://user-images.githubusercontent.com/115127943/226317006-c5bbde0a-aa78-4425-b2c1-a3c9da79c1ac.png)
Thank you for your reply. I'm not sure why I couldn't reproduce the results for the 'airplane' category using your pretrained model, but I re-trained the model from scratch for this category and tested it, and the performance seems to be close to the results reported in the paper. Your work is impressive. I also wanted to ask if it's allowed to train the model on a single category and then test it?

**Comment by Emanuele97x** [comment]
Okay! Let me check maybe there could be a problem with the airplane checkpoint. Yes the models are category-specific in the sense that they are trained/tested separately for each category! Thanks a lot for your interested in our work! I close this issue, feel free to comment or reopen it if needed!

**Comment by engqing** [comment]
I encountered an error while training certain categories. After checking the dataset, I found that the file was indeed missing. I tried to download the dataset again, but the error still persists. Can you help me take a look?
![Snipaste_2023-03-23_16-30-20](https://user-images.githubusercontent.com/115127943/227148148-f62ef743-470f-490d-9640-a74a43b605c5.png)
