### ISSUE TITLE
Can not find L2_ChamferLoss_weighted() 

### ISSUE THREAD

**Issue by tpzou** [diegovalsesia/XMFnet#13]
Hi, @Emanuele97x. When I train the weakly supervised model, the[` loss_cd =  L2_ChamferLoss_weighted()`](https://github.com/diegovalsesia/XMFnet/blob/e1b8487c12cbdc6e60ad8925de32db1dc6868da2/weakly_supervised/train.py#L189) can not be found.  Is there something I'm missing?

**Comment by kistenic-fy** [comment]
Hi! I'm having the same problem. Did you manage to find a solution?

**Comment by Emanuele97x** [comment]
Hi @tpzou and @kistenic-fy, sorry for the late reply, I'll upload everything that is missing by the end of the week! Thanks for the interests in our work! Feel free to contact me (emanuele.aiello@polito.it) if you will need further assistance!

**Comment by Emanuele97x** [comment]
I uploaded everything was missing. You can find the new files at: "/weakly_supervised/decoder/utils/"
