### ISSUE TITLE
Do not have folder "supervised" for third party

### ISSUE THREAD

**Issue by Starak-x** [diegovalsesia/XMFnet#3]
![2022-10-17 16-01-42 的屏幕截图](https://user-images.githubusercontent.com/71073947/196122149-115dfd78-33aa-452e-b58c-ebe65e037ee7.png)
Cloud you please provide this folder for third party? Thank you.

**Comment by Emanuele97x** [comment]
Hi!
The correct path is just "/decoder/utils/..." without supervised in front. I changed the error in setup.sh.

Thanks.
