### ISSUE TITLE
about the dataset.

### ISSUE THREAD

**Issue by CRISZJ** [diegovalsesia/XMFnet#4]
Hello, when we use shapenet-vipc data sets of some categories, there will be data loss. How do you solve it?

**Comment by Emanuele97x** [comment]
Hi!

I have adjusted the dataloader so that any data is corrupted or not found is simply skipped, what do you mean as data loss?

**Comment by CRISZJ** [comment]
> Hi!
> 
> I have adjusted the dataloader so that any data is corrupted or not found is simply skipped, what do you mean as data loss?

ok， thanks for your reply. What I mean is that there will be data loss in the vipc open-source dataset.

**Comment by Emanuele97x** [comment]
We found that it may be a bug that depends on how the dataset has been created.
