### ISSUE TITLE
Where could I find 'train_list2.txt' and 'test_list2.txt' asked in ViPCDataLoader?

### ISSUE THREAD

**Issue by hangyi2000** [diegovalsesia/XMFnet#5]
Where could I find 'train_list2.txt' and 'test_list2.txt' asked in ViPCDataLoader?
I've tried to use 'train_list.txt' and 'test_list.txt' provided in ViPC dataset, but it seems that their formats are different.

**Comment by Emanuele97x** [comment]
Hi!
Yes the list are the same only for the fact that the separator "/" has been changed with ";", sorry for this, I have uploaded the correct lists.
