### ISSUE TITLE
the acquisition of 'ShapeNetViPC-PartPart' point clouds

### ISSUE THREAD

**Issue by hangyi2000** [diegovalsesia/XMFnet#6]
I keep failing in setting up the function ‘randpartial’. Could you please upload a version of 'ShapeNetViPC-PartPart' data? Thanks a lot.

**Comment by Emanuele97x** [comment]
Hi! We are planning to release our version of the dataset in the future, in the meantime you can try to compile randpartial to generate the partialized point cloud with the script we provided.
