### ISSUE TITLE
Can the code work with CUDA11.1

### ISSUE THREAD

**Issue by beibeirory** [diegovalsesia/XMFnet#8]
Thanks for your great work. 
I tested the code with cuda11.1, pytorch 1.10.1, then I got "segmentation fault". Can the code work with cuda11.1?

**Comment by Emanuele97x** [comment]
Hi! We only tested with cuda 10.2, however the code should work with cuda 11.1 with minor modifications, check whether the error is generated by pytorch version or other dependencies!

**Comment by beibeirory** [comment]
Thanks for your replay. How much GPU memory is needed to run the code? What type of your GPUs?

**Comment by Emanuele97x** [comment]
For the training are necessary about 24GBs of GPU memory, we used one Tesla V100 with 32GBs.

**Comment by engqing** [comment]
@Emanuele97x ，I tested the code with cuda10.2，then I also got "segmentation fault". How can I solve this problem? Hope to get your reply.
